### create product

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "SPRING pRICE",
  "price": 250.02,
  "rating": 8,
  "category": {
    "name": "TELLO"
  }
}

### Get products
GET http://localhost:8080/products

### Get Single Product
GET http://localhost:8080/products/4

### Delete
DELETE http://localhost:8080/products/4


### Getter than min price product
GET http://localhost:8080/products/filter?min=223.00

### Less than max price product with catagory
GET http://localhost:8080/products/filters?max=500.00&category="TELLO"
### ByName contain
GET http://localhost:8080/products/filters/byName?prodName="Match Box"